name: Docker Image CI

on:
  push:
    branches: [ mongo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
        run: |
          docker build . --file Dockerfile --tag $DOCKER_ID/notes-api:mongo
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
          docker push $DOCKER_ID/notes-api:mongo